version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  install:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm install mocha-junit-reporter # just for CircleCI
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: mkdir ~/reports
            # Run mocha
            - run: 
              name: test mocha
              command: npm run test
              when: always

            - store_test_results:
                path: reports
                # Upload results

            - store_test_results:
                path: reports

            - store_artifacts:
                path: ./reports/mocha/test-results.xml
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run build
workflows:
  version: 2
  install-test-build:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - test
