version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  install:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm install mocha-junit-reporter # just for CircleCI
  test:
    environment:
      MOCHA_FILE: "$CIRCLE_TEST_REPORTS/test-results.xml"
    executor:
      name: node/default
    steps:
      - checkout
      - run: mkdir test-results
      - node/with-cache:
          steps:
            # Run mocha
            - run: npm run test
            - run: npm run nyc

      - store_test_results:
              path: $CIRCLE_TEST_REPORTS
      
      - store_artifacts:
              path: $CIRCLE_TEST_REPORTS
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run build
workflows:
  version: 2
  install-test-build:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - test
