version: 2.1
orbs:
  node: circleci/node@1.1.6
  codecov: codecov/codecov@1.0.5

jobs:
  install:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm install mocha-junit-reporter # just for CircleCI

  test-users:
    executor:
      name: node/default
    steps:
      - checkout
      - run: mkdir test-results
      - node/with-cache:
          steps:
            # Run mocha
            - run: npm run test-users

  test-users-settings:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            # Run mocha
            - run: npm run test-userSettings
    
  test-ideas:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            # Run mocha
            - run: npm run test-ideas

  test-reports:
    environment:
      MOCHA_FILE: "$CIRCLE_TEST_REPORTS/test-results.xml"
    executor:
      name: node/default
    steps:
      - checkout
      - run: mkdir test-results
      - node/with-cache:
          steps:
            - run: npm run nyc

      - codecov/upload:
          file: coverage.xml
          flags: backend
      - store_test_results:
          path: $CIRCLE_TEST_REPORTS
      - store_artifacts:
          path: $CIRCLE_TEST_REPORTS

  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run build-babel
workflows:
  version: 2
  install-test-build:
    jobs:
      - install
      - test-users:
          requires:
            - install
      - test-users-settings:
          requires:
            - install
            - test-users
      - test-ideas:
          requires:
            - install
            - test-users-settings
      - test-reports:
          requires:
            - test-users
            - test-users-settings
            - test-ideas
      - build:
          requires:
            - test-reports
